### ISSUE TITLE
Determine plan for mirroring site at another domain

### ISSUE THREAD

**Issue by hectcastro** [azavea/rai-measurement-tool#29]
Currently, the contents of this repository are published via GitHub Pages to `rai.azavea.com`. This issue is to determine the most straightforward way to mirror the contents of what's being served at `rai.azavea.com` at `rai.eo.officialstatistics.org`.

Solutions could involve some form of a reverse proxy step that leave the current GitHub Pages pipeline intact, but could also extend to a dual publishing model that involves AWS resources (we have access to a UK ONS AWS account with `eo.officialstatistics.org` setup as a hosted zone).

**Comment by rossbernet** [comment]
@hectcastro what is the LoE of this task?
If it's more than a few hours, I suggest we drop it entirely because the future of the platform is uncertain. 
If it's a couple hours or less, what are the chances it makes it to one of the next couple sprints? It is unfunded at this point and thus not essential. But it could support the client relation moving forward, and they did just reach out to ask about it.

**Comment by hectcastro** [comment]
We've allocated 2 points to come up with a plan, which roughly equates to a day.

The key hangup is around assembling a maintainable solution that provides the desired mirroring effect. A 1-2 hour solution would likely have to sacrifice on these properties a bit.

For example, we could do a one-off copy of the contents of this repository and put them up in the client's AWS account (with a custom domain mapped). The downside of that approach is that any future changes to the contents of this repository would have to be manually copied each time.

**Comment by rossbernet** [comment]
Thanks for the explanation.

Given the uncertainty of the future of the UN global platform, I don't think a long term mirroring effect is worth the day investment. 

I do think a 1 - 2 hour one-off copy would still be worthwhile.
